/* tslint:disable */
/* eslint-disable */
/**
 * Oxpecker OpenAPI Bug Test API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FSharpListOfAnimal } from './fsharp-list-of-animal';

/**
 * Union case: Cons with 2 field(s)
 */
export interface FSharpList1OneOf1 {
    'type': FSharpList1OneOf1Type;
    'head': any;
    'tail': FSharpListOfAnimal;
}

export enum FSharpList1OneOf1Type {
    Cons = 'Cons'
}


