/* tslint:disable */
/* eslint-disable */
/**
 * Oxpecker OpenAPI Bug Test API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FSharpList1OneOf } from './fsharp-list1-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { FSharpListOfAnimal } from './fsharp-list-of-animal';
// May contain unused imports in some cases
// @ts-ignore
import type { FSharpListOfPersonOneOf } from './fsharp-list-of-person-one-of';

/**
 * @type FSharpListOfPerson
 * F# discriminated union type with cases: Empty, Cons
 */
export type FSharpListOfPerson = { type: 'Cons' } & FSharpList1Cons | { type: 'Empty' } & FSharpList1Empty;


