/* tslint:disable */
/* eslint-disable */
/**
 * Oxpecker OpenAPI Bug Test API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Union case: Triangle with 2 field(s)
 */
export interface ShapeOneOf2 {
    'type': ShapeOneOf2Type;
    'base_': number;
    'height': number;
}

export enum ShapeOneOf2Type {
    Triangle = 'Triangle'
}


