/* tslint:disable */
/* eslint-disable */
/**
 * Oxpecker OpenAPI Bug Test API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Union case: Circle with 1 field(s)
 */
export interface ShapeCircle {
    'type': ShapeCircleType;
    'radius': number;
}

export enum ShapeCircleType {
    Circle = 'Circle'
}


