/* tslint:disable */
/* eslint-disable */
/**
 * Oxpecker OpenAPI Bug Test API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AnimalColor } from '../models';
// @ts-ignore
import type { Shape } from '../models';
/**
 * ExamplesApi - axios parameter creator
 */
export const ExamplesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns a single AnimalColor (Brown) to test enum-like union schema generation
         * @summary Get a single AnimalColor union value
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSingleAnimalColor: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/test-single-color`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a single Shape (Circle) to test union schema generation
         * @summary Get a single Shape union value
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSingleShape: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/test-single-shape`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns dummy data for all union types (SimpleStatus, Shape, PaymentMethod, Result, ApiResponse, ContactInfo, AnimalColor). Use this to visualize the generated OpenAPI schemas for F# discriminated unions.
         * @summary Get examples of all F# union types
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUnionExamples: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/union-examples`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExamplesApi - functional programming interface
 */
export const ExamplesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExamplesApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns a single AnimalColor (Brown) to test enum-like union schema generation
         * @summary Get a single AnimalColor union value
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSingleAnimalColor(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AnimalColor>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSingleAnimalColor(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExamplesApi.getSingleAnimalColor']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a single Shape (Circle) to test union schema generation
         * @summary Get a single Shape union value
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSingleShape(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Shape>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSingleShape(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExamplesApi.getSingleShape']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns dummy data for all union types (SimpleStatus, Shape, PaymentMethod, Result, ApiResponse, ContactInfo, AnimalColor). Use this to visualize the generated OpenAPI schemas for F# discriminated unions.
         * @summary Get examples of all F# union types
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUnionExamples(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUnionExamples(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExamplesApi.getUnionExamples']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ExamplesApi - factory interface
 */
export const ExamplesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExamplesApiFp(configuration)
    return {
        /**
         * Returns a single AnimalColor (Brown) to test enum-like union schema generation
         * @summary Get a single AnimalColor union value
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSingleAnimalColor(options?: RawAxiosRequestConfig): AxiosPromise<AnimalColor> {
            return localVarFp.getSingleAnimalColor(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a single Shape (Circle) to test union schema generation
         * @summary Get a single Shape union value
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSingleShape(options?: RawAxiosRequestConfig): AxiosPromise<Shape> {
            return localVarFp.getSingleShape(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns dummy data for all union types (SimpleStatus, Shape, PaymentMethod, Result, ApiResponse, ContactInfo, AnimalColor). Use this to visualize the generated OpenAPI schemas for F# discriminated unions.
         * @summary Get examples of all F# union types
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUnionExamples(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getUnionExamples(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ExamplesApi - interface
 */
export interface ExamplesApiInterface {
    /**
     * Returns a single AnimalColor (Brown) to test enum-like union schema generation
     * @summary Get a single AnimalColor union value
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSingleAnimalColor(options?: RawAxiosRequestConfig): AxiosPromise<AnimalColor>;

    /**
     * Returns a single Shape (Circle) to test union schema generation
     * @summary Get a single Shape union value
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSingleShape(options?: RawAxiosRequestConfig): AxiosPromise<Shape>;

    /**
     * Returns dummy data for all union types (SimpleStatus, Shape, PaymentMethod, Result, ApiResponse, ContactInfo, AnimalColor). Use this to visualize the generated OpenAPI schemas for F# discriminated unions.
     * @summary Get examples of all F# union types
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUnionExamples(options?: RawAxiosRequestConfig): AxiosPromise<any>;

}

/**
 * ExamplesApi - object-oriented interface
 */
export class ExamplesApi extends BaseAPI implements ExamplesApiInterface {
    /**
     * Returns a single AnimalColor (Brown) to test enum-like union schema generation
     * @summary Get a single AnimalColor union value
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSingleAnimalColor(options?: RawAxiosRequestConfig) {
        return ExamplesApiFp(this.configuration).getSingleAnimalColor(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a single Shape (Circle) to test union schema generation
     * @summary Get a single Shape union value
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSingleShape(options?: RawAxiosRequestConfig) {
        return ExamplesApiFp(this.configuration).getSingleShape(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns dummy data for all union types (SimpleStatus, Shape, PaymentMethod, Result, ApiResponse, ContactInfo, AnimalColor). Use this to visualize the generated OpenAPI schemas for F# discriminated unions.
     * @summary Get examples of all F# union types
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUnionExamples(options?: RawAxiosRequestConfig) {
        return ExamplesApiFp(this.configuration).getUnionExamples(options).then((request) => request(this.axios, this.basePath));
    }
}

