/* tslint:disable */
/* eslint-disable */
/**
 * Oxpecker OpenAPI Bug Test API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { FSharpListOfAnimal } from '../models';
// @ts-ignore
import type { FSharpListOfPerson } from '../models';
/**
 * SearchApi - axios parameter creator
 */
export const SearchApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns a list of animals matching the search criteria provided in the query parameters.
         * @summary Search for animals based on query parameters
         * @param {string} [name] Filter by name (required)
         * @param {string} [species] Filter by species (optional)
         * @param {boolean} [vaccinated] Filter by vaccination status (optional)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchAnimals: async (name?: string, species?: string, vaccinated?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/animals`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['Name'] = name;
            }

            if (species !== undefined) {
                localVarQueryParameter['Species'] = species;
            }

            if (vaccinated !== undefined) {
                localVarQueryParameter['Vaccinated'] = vaccinated;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a list of persons matching the search criteria provided in the query parameters.
         * @summary Search for persons based on query parameters
         * @param {string} [name] Filter by name (optional)
         * @param {string} [occupation] Filter by occupation (optional)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchPersons: async (name?: string, occupation?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/persons`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['Name'] = name;
            }

            if (occupation !== undefined) {
                localVarQueryParameter['Occupation'] = occupation;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SearchApi - functional programming interface
 */
export const SearchApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SearchApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns a list of animals matching the search criteria provided in the query parameters.
         * @summary Search for animals based on query parameters
         * @param {string} [name] Filter by name (required)
         * @param {string} [species] Filter by species (optional)
         * @param {boolean} [vaccinated] Filter by vaccination status (optional)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchAnimals(name?: string, species?: string, vaccinated?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FSharpListOfAnimal>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchAnimals(name, species, vaccinated, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SearchApi.searchAnimals']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a list of persons matching the search criteria provided in the query parameters.
         * @summary Search for persons based on query parameters
         * @param {string} [name] Filter by name (optional)
         * @param {string} [occupation] Filter by occupation (optional)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchPersons(name?: string, occupation?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FSharpListOfPerson>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchPersons(name, occupation, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SearchApi.searchPersons']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SearchApi - factory interface
 */
export const SearchApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SearchApiFp(configuration)
    return {
        /**
         * Returns a list of animals matching the search criteria provided in the query parameters.
         * @summary Search for animals based on query parameters
         * @param {SearchApiSearchAnimalsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchAnimals(requestParameters: SearchApiSearchAnimalsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<FSharpListOfAnimal> {
            return localVarFp.searchAnimals(requestParameters.name, requestParameters.species, requestParameters.vaccinated, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a list of persons matching the search criteria provided in the query parameters.
         * @summary Search for persons based on query parameters
         * @param {SearchApiSearchPersonsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchPersons(requestParameters: SearchApiSearchPersonsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<FSharpListOfPerson> {
            return localVarFp.searchPersons(requestParameters.name, requestParameters.occupation, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SearchApi - interface
 */
export interface SearchApiInterface {
    /**
     * Returns a list of animals matching the search criteria provided in the query parameters.
     * @summary Search for animals based on query parameters
     * @param {SearchApiSearchAnimalsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchAnimals(requestParameters?: SearchApiSearchAnimalsRequest, options?: RawAxiosRequestConfig): AxiosPromise<FSharpListOfAnimal>;

    /**
     * Returns a list of persons matching the search criteria provided in the query parameters.
     * @summary Search for persons based on query parameters
     * @param {SearchApiSearchPersonsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchPersons(requestParameters?: SearchApiSearchPersonsRequest, options?: RawAxiosRequestConfig): AxiosPromise<FSharpListOfPerson>;

}

/**
 * Request parameters for searchAnimals operation in SearchApi.
 */
export interface SearchApiSearchAnimalsRequest {
    /**
     * Filter by name (required)
     */
    readonly name?: string

    /**
     * Filter by species (optional)
     */
    readonly species?: string

    /**
     * Filter by vaccination status (optional)
     */
    readonly vaccinated?: boolean
}

/**
 * Request parameters for searchPersons operation in SearchApi.
 */
export interface SearchApiSearchPersonsRequest {
    /**
     * Filter by name (optional)
     */
    readonly name?: string

    /**
     * Filter by occupation (optional)
     */
    readonly occupation?: string
}

/**
 * SearchApi - object-oriented interface
 */
export class SearchApi extends BaseAPI implements SearchApiInterface {
    /**
     * Returns a list of animals matching the search criteria provided in the query parameters.
     * @summary Search for animals based on query parameters
     * @param {SearchApiSearchAnimalsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public searchAnimals(requestParameters: SearchApiSearchAnimalsRequest = {}, options?: RawAxiosRequestConfig) {
        return SearchApiFp(this.configuration).searchAnimals(requestParameters.name, requestParameters.species, requestParameters.vaccinated, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a list of persons matching the search criteria provided in the query parameters.
     * @summary Search for persons based on query parameters
     * @param {SearchApiSearchPersonsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public searchPersons(requestParameters: SearchApiSearchPersonsRequest = {}, options?: RawAxiosRequestConfig) {
        return SearchApiFp(this.configuration).searchPersons(requestParameters.name, requestParameters.occupation, options).then((request) => request(this.axios, this.basePath));
    }
}

