/* tslint:disable */
/* eslint-disable */
/**
 * Oxpecker OpenAPI Bug Test API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { FSharpListOfAnimal } from '../models';
/**
 * TestingApi - axios parameter creator
 */
export const TestingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns sample animals to verify how AnimalColor option is serialized
         * @summary Test AnimalColor serialization
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testAnimalColor: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/test-animal-color`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Test endpoint to verify that numbers can be deserialized from strings when using AllowReadingFromString. This endpoint accepts JSON with numbers that might be strings.
         * @summary Test number deserialization with AllowReadingFromString
         * @param {any} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testNumberDeserialization: async (body: any, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('testNumberDeserialization', 'body', body)
            const localVarPath = `/test-number-deserialization`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Runs comprehensive tests of F# union type serialization/deserialization using FSharp.SystemTextJson
         * @summary Test F# union type serialization
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testUnionSerialization: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/test-union-serialization`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TestingApi - functional programming interface
 */
export const TestingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TestingApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns sample animals to verify how AnimalColor option is serialized
         * @summary Test AnimalColor serialization
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testAnimalColor(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FSharpListOfAnimal>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testAnimalColor(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestingApi.testAnimalColor']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Test endpoint to verify that numbers can be deserialized from strings when using AllowReadingFromString. This endpoint accepts JSON with numbers that might be strings.
         * @summary Test number deserialization with AllowReadingFromString
         * @param {any} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testNumberDeserialization(body: any, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testNumberDeserialization(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestingApi.testNumberDeserialization']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Runs comprehensive tests of F# union type serialization/deserialization using FSharp.SystemTextJson
         * @summary Test F# union type serialization
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testUnionSerialization(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testUnionSerialization(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestingApi.testUnionSerialization']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TestingApi - factory interface
 */
export const TestingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TestingApiFp(configuration)
    return {
        /**
         * Returns sample animals to verify how AnimalColor option is serialized
         * @summary Test AnimalColor serialization
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testAnimalColor(options?: RawAxiosRequestConfig): AxiosPromise<FSharpListOfAnimal> {
            return localVarFp.testAnimalColor(options).then((request) => request(axios, basePath));
        },
        /**
         * Test endpoint to verify that numbers can be deserialized from strings when using AllowReadingFromString. This endpoint accepts JSON with numbers that might be strings.
         * @summary Test number deserialization with AllowReadingFromString
         * @param {TestingApiTestNumberDeserializationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testNumberDeserialization(requestParameters: TestingApiTestNumberDeserializationRequest, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.testNumberDeserialization(requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * Runs comprehensive tests of F# union type serialization/deserialization using FSharp.SystemTextJson
         * @summary Test F# union type serialization
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testUnionSerialization(options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.testUnionSerialization(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TestingApi - interface
 */
export interface TestingApiInterface {
    /**
     * Returns sample animals to verify how AnimalColor option is serialized
     * @summary Test AnimalColor serialization
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testAnimalColor(options?: RawAxiosRequestConfig): AxiosPromise<FSharpListOfAnimal>;

    /**
     * Test endpoint to verify that numbers can be deserialized from strings when using AllowReadingFromString. This endpoint accepts JSON with numbers that might be strings.
     * @summary Test number deserialization with AllowReadingFromString
     * @param {TestingApiTestNumberDeserializationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testNumberDeserialization(requestParameters: TestingApiTestNumberDeserializationRequest, options?: RawAxiosRequestConfig): AxiosPromise<string>;

    /**
     * Runs comprehensive tests of F# union type serialization/deserialization using FSharp.SystemTextJson
     * @summary Test F# union type serialization
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testUnionSerialization(options?: RawAxiosRequestConfig): AxiosPromise<string>;

}

/**
 * Request parameters for testNumberDeserialization operation in TestingApi.
 */
export interface TestingApiTestNumberDeserializationRequest {
    readonly body: any
}

/**
 * TestingApi - object-oriented interface
 */
export class TestingApi extends BaseAPI implements TestingApiInterface {
    /**
     * Returns sample animals to verify how AnimalColor option is serialized
     * @summary Test AnimalColor serialization
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testAnimalColor(options?: RawAxiosRequestConfig) {
        return TestingApiFp(this.configuration).testAnimalColor(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Test endpoint to verify that numbers can be deserialized from strings when using AllowReadingFromString. This endpoint accepts JSON with numbers that might be strings.
     * @summary Test number deserialization with AllowReadingFromString
     * @param {TestingApiTestNumberDeserializationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testNumberDeserialization(requestParameters: TestingApiTestNumberDeserializationRequest, options?: RawAxiosRequestConfig) {
        return TestingApiFp(this.configuration).testNumberDeserialization(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Runs comprehensive tests of F# union type serialization/deserialization using FSharp.SystemTextJson
     * @summary Test F# union type serialization
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testUnionSerialization(options?: RawAxiosRequestConfig) {
        return TestingApiFp(this.configuration).testUnionSerialization(options).then((request) => request(this.axios, this.basePath));
    }
}

